name: Sync with upstream

on:
  # 手动触发同步
  workflow_dispatch:
  # 定时触发同步（例如每天凌晨2点）
  schedule:
    - cron: '0 2 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.UPSTREAM_SYNC_TOKEN }}
          fetch-depth: 0  # 获取所有历史记录

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/triton-lang/triton.git
          git remote -v

      - name: Fetch upstream branches
        run: |
          git fetch upstream
          git branch -a

      - name: Sync specific branch (e.g., main)
        run: |
          git checkout origin/release/3.2.x  # 切换到要同步的本地分支
          git reset --hard upstream/release/3.2.x  # 重置为上游分支
          git push -f origin release/3.2.x  # 强制推送到当前仓库
